# **Theoretical Questions:**

**1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**

**Ans.**

NumPy is a Python package for scientific computing that supports large, multi-dimensional arrays and matrices, offering mathematical functions for operations on these arrays. Its key advantages include efficient storage, faster array operations due to its C implementation, support for element-wise operations, broadcasting, and vectorization, and easy integration with various data science and machine learning libraries like Pandas, SciPy, and TensorFlow. NumPy's homogeneous nature ensures efficient storage and faster operations, making it a valuable tool for scientific computing.

___



**2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?**

**Ans.**

The np.mean() function calculates the arithmetic mean of array elements, while the np.average() function calculates the weighted average, allowing for weights to influence each element's contribution to the final average.

**Example:**


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# Simple mean
mean_val = np.mean(arr)
print("Mean: ", mean_val)

# Weighted average
weights = np.array([1, 1, 1, 4])
average_val = np.average(arr, weights=weights)
print("Average: ",average_val)

Mean:  2.5
Average:  3.142857142857143


___

**3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.**

**Ans.**

**1D Array:**


In [ ]:
arr_1d = np.array([1, 2, 3, 4])
reversed_1d = arr_1d[::-1]
print("Reversed 1D Array:", reversed_1d)


Reversed 1D Array: [4 3 2 1]


**2D Array:**

In [ ]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
reversed_rows = arr_2d[::-1, :] #reversed rows
reversed_columns = arr_2d[:, ::-1] #reversed columns
print("Reversed Rows:\n", reversed_rows)
print("Reversed Columns:\n", reversed_columns)


Reversed Rows:
 [[5 6]
 [3 4]
 [1 2]]
Reversed Columns:
 [[2 1]
 [4 3]
 [6 5]]


___

**4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.**

**Ans.**
The dtype attribute in NumPy arrays indicates the data type of elements, which determines memory usage and operations. Proper data type optimization can improve performance, particularly with large arrays, making it crucial for efficient data management.

Data types are crucial in memory management and performance in computing, especially when working with large datasets or performing computationally intensive tasks. In Python and NumPy, each data type corresponds to a specific amount of memory. Integers, such as int8, take 1 byte per element, while int32, int32, and int64 take 4 and 8 bytes per element, respectively. Floats, like float32, take 4 and 8 bytes per element. By choosing the appropriate data type, you can optimize memory usage, such as using int8 instead of int32 or int64 for large datasets.

Data types significantly impact the performance of operations on arrays, with smaller data types resulting in faster computations due to less data movement between memory and the processor. This is especially important in large-scale numerical computations like scientific computing, machine learning, and data analysis. Additionally, smaller data types enable more elements to be processed in parallel within the CPU's registers, resulting in faster execution in vectorization and SIMD (Single Instruction, Multiple Data) applications.

___
# **5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

**Ans.**

NumPy's ndarray is a fixed-size, homogeneous N-dimensional array with efficient element-wise operations and broadcasting. Its memory efficiency is higher than Python lists due to homogeneous types, and its performance is faster due to optimized C-based computations. Ndarrays support a wide range of mathematical operations natively.


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


___
# **6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

Ans.

NumPy arrays are more efficient than Python lists due to their single memory block usage and vectorized operations, which allow operations on entire arrays without loops, resulting in significant speedups.


In [1]:
import numpy as np
import time

# Large data
size = int(1e6)
list_data = list(range(size))
array_data = np.arange(size)

# Time operation on list
start_time = time.time()
list_sum = sum(list_data)
list_time = time.time() - start_time

# Time operation on NumPy array
start_time = time.time()
array_sum = np.sum(array_data)
array_time = time.time() - start_time

print(f"List time: {list_time}, NumPy array time: {array_time}")


List time: 0.011570453643798828, NumPy array time: 0.004550933837890625


___
# **7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.**

Ans.

The vstack() function stacks arrays vertically by appending rows, while the hstack() function stacks arrays horizontally by appending columns, resulting in a larger array.

Example:



In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertical stack
v_stacked = np.vstack((arr1, arr2))
print("Vertical Stack: ",v_stacked)
print("\n")

# Horizontal stack
h_stacked = np.hstack((arr1, arr2))
print("Horizontal Stack: ",h_stacked)


Vertical Stack:  [[1 2 3]
 [4 5 6]]


Horizontal Stack:  [1 2 3 4 5 6]


___
# **8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.**

Ans.

Fliplr() and flipud() are functions that flip an array left to right along the horizontal axis and upside down along the vertical axis respectively.

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Fliplr (left to right)
flipped_lr = np.fliplr(arr)
print(flipped_lr)
print("\n")
# Flipud (upside down)
flipped_ud = np.flipud(arr)
print(flipped_ud)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


[[7 8 9]
 [4 5 6]
 [1 2 3]]


___
# **9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

Ans.

NumPy's array_split() method splits an array into multiple sub-arrays, distributing the remainder evenly, ensuring all sub-arrays have nearly equal sizes.

In [6]:
arr = np.array([1, 2, 3, 4, 5])

# Split into 3 parts
split_arr = np.array_split(arr, 3)
print(split_arr)


[array([1, 2]), array([3, 4]), array([5])]


___
# **10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations**

Ans.

Vectorization and broadcasting are two programming techniques that simplify and speed up code by applying operations to entire arrays and automatically expanding them to a common shape without data copying.

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vectorized addition (element-wise)
sum_arr = arr1 + arr2
print(sum_arr)

# Broadcasting: adding a scalar to an array
scalar = 10
result = arr1 + scalar
print(result)


[5 7 9]
[11 12 13]


# **Practical Questions:**

___
# **1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

In [9]:
import numpy as np
import random
arr=np.random.randint(1,100,size=(3,3))
print(arr)
print("The interchanged rows and columns are: \n")
print(arr.T)

[[79 15 65]
 [42 14 43]
 [ 2 72 73]]
The interchanged rows and columns are: 

[[79 42  2]
 [15 14 72]
 [65 43 73]]


# **2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array**

In [13]:
import numpy as np
import random
arr=np.arange(10)
print(arr)
print("The reshaped 2x5 array is: \n")
print(arr.reshape(2,5))
print("\n")
print("The reshaped 5x2 array is: \n")
print(arr.reshape(5,2))

[0 1 2 3 4 5 6 7 8 9]
The reshaped 2x5 array is: 

[[0 1 2 3 4]
 [5 6 7 8 9]]


The reshaped 5x2 array is: 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# **3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [14]:
import numpy as np
arr_4x4 = np.random.rand(4, 4)

arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)

print("4x4 Array with Random Float Values:")
print(arr_4x4)
print("\n6x6 Array with Border of Zeros:")
print(arr_6x6)


4x4 Array with Random Float Values:
[[0.3776494  0.29218305 0.93011009 0.74779416]
 [0.50659868 0.73493712 0.92152965 0.48232729]
 [0.05988615 0.01512269 0.22257271 0.52566745]
 [0.50688853 0.3751437  0.16093827 0.1764903 ]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.3776494  0.29218305 0.93011009 0.74779416 0.        ]
 [0.         0.50659868 0.73493712 0.92152965 0.48232729 0.        ]
 [0.         0.05988615 0.01512269 0.22257271 0.52566745 0.        ]
 [0.         0.50688853 0.3751437  0.16093827 0.1764903  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# **4. Using NumPy, create an array of integers from 10 to 60 with a step of 5**

In [15]:
import numpy as np
arr=np.arange(10,60,5)
print(arr)

[10 15 20 25 30 35 40 45 50 55]


# **5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.**

In [17]:
import numpy as np
arr=np.array(['python', 'numpy', 'pandas'])
print(arr)
print("The uppercase array is: \n")
print(np.char.upper(arr))
print("\n")
print("The lowercase array is: \n")
print(np.char.lower(arr))
print("\n")
print("The titlecase array is: \n")
print(np.char.title(arr))

['python' 'numpy' 'pandas']
The uppercase array is: 

['PYTHON' 'NUMPY' 'PANDAS']


The lowercase array is: 

['python' 'numpy' 'pandas']


The titlecase array is: 

['Python' 'Numpy' 'Pandas']


# **6. Generate a NumPy array of words. Insert a space between each character of every word in the array**

In [18]:
import numpy as np

words = np.array(['apple', 'banana', 'cherry'])
spaced_words = np.char.join(' ', words)

print(spaced_words)

['a p p l e' 'b a n a n a' 'c h e r r y']


# **7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [19]:
import numpy as np
import random
arr=np.random.randint(1,100,size=(2,2))
arr1=np.random.randint(1,100,size=(2,2))
print(arr)
print("\n")
print(arr1)
print("\n")
print("The element-wise addition is: \n")
print(np.add(arr,arr1))
print("\n")
print("The element-wise subtraction is: \n")
print(np.subtract(arr,arr1))
print("\n")
print("The element-wise multiplication is: \n")
print(np.multiply(arr,arr1))
print("\n")
print("The element-wise division is: \n")
print(np.divide(arr,arr1))



[[44 26]
 [23 89]]


[[97 94]
 [71 93]]


The element-wise addition is: 

[[141 120]
 [ 94 182]]


The element-wise subtraction is: 

[[-53 -68]
 [-48  -4]]


The element-wise multiplication is: 

[[4268 2444]
 [1633 8277]]


The element-wise division is: 

[[0.45360825 0.27659574]
 [0.32394366 0.95698925]]


# **8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**


In [20]:
import numpy as np
arr=np.identity(5)
print(arr)
print("\n")
print("The diagonal elements are: \n")
print(np.diag(arr))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


The diagonal elements are: 

[1. 1. 1. 1. 1.]


# **9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers inthis array.**

In [21]:
import numpy as np
arr=np.random.randint(0,1000,size=(100))
print(arr)
print("\n")
print("The prime numbers are: \n")
for i in arr:
  if i>1:
    for j in range(2,i):
      if i%j==0:
        break
    else:
      print(i)

[339 529 951 938 467 340 403  90 754 327 466 848 248 321 601 813 144 422
 578 214 855 287 835  70 846 175 765 217 695  14  61 243 479 316 198 210
 476 877 772 417 245 693 737  24 500 853 566 696 360 658 825 152 791 690
  18 816 643 143 539 721 603 880  72  60 525 566 953 976 627 150  74 199
 995 993 832 913 599 425 603 161 460 666 637 484 823 852 883 812 903 435
 405 253 851 735 585 757 119 573 503  55]


The prime numbers are: 

467
601
61
479
877
853
643
953
199
599
823
883
757
503


# **10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.**

In [22]:
import numpy as np
arr=np.random.randint(0,100,size=(30))
print(arr)
print("\n")
print("The weekly averages are: \n")
print(np.mean(arr))


[63 57 40 10 54 92 26  2 13 97 61 57 45 30 76 24 76 85 54 75 19  1 58 18
 56 47 78  3 12 69]


The weekly averages are: 

46.6
